name: Continuous Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install Clojure and Leiningen
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          lein: 2.9.8

      - name: Build standalone JAR
        run: lein with-profile uberjar uberjar

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: target/map-tile-cutter-*-standalone.jar
